CREATE DATABASE LocadoraDeVeiculos;

USE LocadoraDeVeiculos;

CREATE TABLE
    Cliente (
        DATA_NASC DATE,
        fk_TELEFONE_TELEFONE INT,
        CPF VARCHAR(11),
        ID_CLI INT AUTO_INCREMENT NOT NULL PRIMARY KEY
    );

CREATE TABLE
    Funcionario (
        ID_FUNC INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        NOME_FUNC VARCHAR(255),
        CARGO VARCHAR(255)
    );

CREATE TABLE
    Movimento (
        ID_MOVIMENTO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        ID_FUNC INT,
        ID_VEIC INT,
        ID_CLI INT,
        ALUGUEL FLOAT,
        RETIRADA DATE,
        DEVOLUCAO DATE,
        FOREIGN KEY (ID_FUNC) REFERENCES Funcionario (ID_FUNC),
        FOREIGN KEY (ID_VEIC) REFERENCES Veiculo (ID_VEIC),
        FOREIGN KEY (ID_CLI) REFERENCES Cliente (ID_CLI)
    );

CREATE TABLE
    Veiculo (
        ID_VEIC INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        PLACA VARCHAR(7),
        MARCA VARCHAR(255),
        MODELO VARCHAR(255),
        COR VARCHAR(255),
        ANO INT,
        STATUS VARCHAR(255)
    );

CREATE TABLE
    Oficina (
        ID_SERVICO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        LAVAGEM VARCHAR(255),
        MANUNTENCAO VARCHAR(255),
        ID_FUNC INT,
        ID_VEIC INT
    );

CREATE TABLE
    TELEFONE (
        TELEFONE_PK INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        TELEFONE VARCHAR(15)
    );

CREATE TABLE
    SOLICITA (
        FK_Movimento_ID_MOVIMENTO INT,
        FK_Cliente_ID_CLI INT,
        PRIMARY KEY (FK_Movimento_ID_MOVIMENTO, FK_Cliente_ID_CLI),
        FOREIGN KEY (FK_Movimento_ID_MOVIMENTO) REFERENCES Movimento (ID_MOVIMENTO),
        FOREIGN KEY (FK_Cliente_ID_CLI) REFERENCES Cliente (ID_CLI)
    );

CREATE TABLE
    ATENDE (
        FK_Movimento_ID_MOVIMENTO INT,
        FK_Funcionario_ID_FUNC INT,
        PRIMARY KEY (FK_Movimento_ID_MOVIMENTO, FK_Funcionario_ID_FUNC),
        FOREIGN KEY (FK_Movimento_ID_MOVIMENTO) REFERENCES Movimento (ID_MOVIMENTO),
        FOREIGN KEY (FK_Funcionario_ID_FUNC) REFERENCES Funcionario (ID_FUNC)
    );

CREATE TABLE
    INCLUIR (
        FK_Veiculo_ID_VEIC INT,
        FK_Movimento_ID_MOVIMENTO INT,
        PRIMARY KEY (FK_Veiculo_ID_VEIC, FK_Movimento_ID_MOVIMENTO),
        FOREIGN KEY (FK_Veiculo_ID_VEIC) REFERENCES Veiculo (ID_VEIC),
        FOREIGN KEY (FK_Movimento_ID_MOVIMENTO) REFERENCES Movimento (ID_MOVIMENTO)
    );

CREATE TABLE
    ENVIA (
        FK_Oficina_ID_SERVICO INT,
        FK_Funcionario_ID_FUNC INT,
        PRIMARY KEY (FK_Oficina_ID_SERVICO, FK_Funcionario_ID_FUNC),
        FOREIGN KEY (FK_Oficina_ID_SERVICO) REFERENCES Oficina (ID_SERVICO),
        FOREIGN KEY (FK_Funcionario_ID_FUNC) REFERENCES Funcionario (ID_FUNC)
    );

CREATE TABLE
    LIBERA (
        FK_Oficina_ID_SERVICO INT,
        FK_Veiculo_ID_VEIC INT,
        PRIMARY KEY (FK_Oficina_ID_SERVICO, FK_Veiculo_ID_VEIC),
        FOREIGN KEY (FK_Oficina_ID_SERVICO) REFERENCES Oficina (ID_SERVICO),
        FOREIGN KEY (FK_Veiculo_ID_VEIC) REFERENCES Veiculo (ID_VEIC)
    );

ALTER TABLE Cliente ADD CONSTRAINT FK_Cliente_2 FOREIGN KEY (fk_TELEFONE_TELEFONE) REFERENCES TELEFONE (TELEFONE_PK);

ALTER TABLE SOLICITA ADD CONSTRAINT FK_SOLICITA_1 FOREIGN KEY (FK_Movimento_ID_MOVIMENTO) REFERENCES Movimento (ID_MOVIMENTO);

ALTER TABLE SOLICITA ADD CONSTRAINT FK_SOLICITA_2 FOREIGN KEY (FK_Cliente_ID_CLI) REFERENCES Cliente (ID_CLI);

ALTER TABLE ATENDE ADD CONSTRAINT FK_ATENDE_1 FOREIGN KEY (FK_Movimento_ID_MOVIMENTO) REFERENCES Movimento (ID_MOVIMENTO);

ALTER TABLE ATENDE ADD CONSTRAINT FK_ATENDE_2 FOREIGN KEY (FK_Funcionario_ID_FUNC) REFERENCES Funcionario (ID_FUNC);

ALTER TABLE INCLUIR ADD CONSTRAINT FK_INCLUIR_1 FOREIGN KEY (FK_Veiculo_ID_VEIC) REFERENCES Veiculo (ID_VEIC);

ALTER TABLE INCLUIR ADD CONSTRAINT FK_INCLUIR_2 FOREIGN KEY (FK_Movimento_ID_MOVIMENTO) REFERENCES Movimento (ID_MOVIMENTO);

ALTER TABLE ENVIA ADD CONSTRAINT FK_ENVIA_1 FOREIGN KEY (FK_Oficina_ID_SERVICO) REFERENCES Oficina (ID_SERVICO);

ALTER TABLE ENVIA ADD CONSTRAINT FK_ENVIA_2 FOREIGN KEY (FK_Funcionario_ID_FUNC) REFERENCES Funcionario (ID_FUNC);

ALTER TABLE LIBERA ADD CONSTRAINT FK_LIBERA_1 FOREIGN KEY (FK_Oficina_ID_SERVICO) REFERENCES Oficina (ID_SERVICO);

ALTER TABLE LIBERA ADD CONSTRAINT FK_LIBERA_2 FOREIGN KEY (FK_Veiculo_ID_VEIC) REFERENCES Veiculo (ID_VEIC);